version: '3'
services:
  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on: 
    - mongodb
  mongodb:
    image: mongo
    ports:
    - 27018:27017
  postgresdb:
    image: postgres
    container_name: postgres_container
    ports:
    - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tweet_data
  etl:
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on: 
    - mongodb
    depends_on:
    - postgresdb

  slackbot:
    build: slackbot/
    depends_on: 
    - postgresdb

